name: "Frontend Usability Audit"
description: "Run Lighthouse and frontend usability analysis"

inputs:
  framework:
    description: "Frontend framework"
    required: true

outputs:
  usability_score:
    description: "Usability score out of 100"
    value: ${{ steps.audit.outputs.usability_score }}
  lighthouse_performance:
    description: "Lighthouse performance score"
    value: ${{ steps.audit.outputs.lighthouse_performance }}
  lighthouse_accessibility:
    description: "Lighthouse accessibility score"
    value: ${{ steps.audit.outputs.lighthouse_accessibility }}
  lighthouse_seo:
    description: "Lighthouse SEO score"
    value: ${{ steps.audit.outputs.lighthouse_seo }}

runs:
  using: "composite"
  steps:
    - name: 🎨 Frontend Usability Analysis
      id: audit
      shell: bash
      env:
        FRAMEWORK: ${{ inputs.framework }}
      run: |
        cd ${{ github.action_path }}

        # Install required dependencies
        npm install --silent @actions/core

        # Run the frontend audit script
        node frontend-audit.js
